[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Environment variables for production
# Add these in Netlify dashboard:
# MP_ACCESS_TOKEN = "APP_USR-your-mercado-pago-access-token"
# VITE_MP_PUBLIC_KEY = "your-mercado-pago-public-key" (optional, for SDK)